const fs = require('fs');
const path = require('path');

function readEnvFile() {
  const envPath = path.join(__dirname, '.env');
  const values = {};

  if (fs.existsSync(envPath)) {
    const lines = fs.readFileSync(envPath, 'utf8').split(/\r?\n/);
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const parts = trimmed.split('=');
      if (parts.length >= 2) {
        const key = parts[0].trim();
        const val = parts.slice(1).join('=').trim().replace(/^['"]|['"]$/g, '');
        values[key] = val;
      }
    }
  }

  return values;
}

function pickEnv(key, fileValues) {
  if (process.env[key] && String(process.env[key]).trim()) {
    return String(process.env[key]).trim();
  }
  if (fileValues[key] && String(fileValues[key]).trim()) {
    return String(fileValues[key]).trim();
  }
  return '';
}

const fileValues = readEnvFile();

const url = pickEnv('SUPABASE_URL', fileValues);
const anonKey = pickEnv('SUPABASE_ANON_KEY', fileValues);
const logtoOidcProvider = pickEnv('LOGTO_OIDC_PROVIDER', fileValues) || 'custom:nlc-logto';
const appBaseUrl = pickEnv('APP_BASE_URL', fileValues);

const configContent = `// App runtime configuration
// Generated by build-config.js from .env — do not edit manually.
const SUPABASE_CONFIG = {
  url: "${url}",
  anonKey: "${anonKey}"
};

const APP_CONFIG = {
  logtoOidcProvider: "${logtoOidcProvider}",
  appBaseUrl: "${appBaseUrl}"
};
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), configContent, 'utf8');
console.log('---');
console.log('Successfully regenerated config.js');
console.log(`SUPABASE_URL: ${url ? url : '(not set)'}`);
console.log(`SUPABASE_ANON_KEY: ${anonKey ? 'loaded' : '(not set)'}`);
console.log(`LOGTO_OIDC_PROVIDER: ${logtoOidcProvider}`);
console.log(`APP_BASE_URL: ${appBaseUrl || '(not set)'}`);
console.log('---');
